cmake_minimum_required(VERSION 3.22.1)
project(minecraft_es)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT DEFINED ANDROID_NDK)
    if(DEFINED ENV{ANDROID_NDK})
        set(ANDROID_NDK $ENV{ANDROID_NDK})
    elseif(DEFINED CMAKE_ANDROID_NDK)
        set(ANDROID_NDK ${CMAKE_ANDROID_NDK})
    endif()
endif()
include(FetchContent)
FetchContent_Declare(glm GIT_REPOSITORY https://github.com/g-truc/glm.git GIT_TAG 1.0.1)
set(GLM_BUILD_TESTS OFF)
set(GLM_BUILD_INSTALL OFF)
FetchContent_MakeAvailable(glm)
set(NATIVE_APP_GLUE_C ${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c)
set(NATIVE_APP_GLUE_H ${ANDROID_NDK}/sources/android/native_app_glue)
add_library(minecraft_es SHARED main.cpp Shader.cpp PerlinNoise.cpp Block.cpp Chunk.cpp World.cpp Player.cpp Renderer.cpp TextureAtlas.cpp InputManager.cpp UI.cpp SaveManager.cpp ${NATIVE_APP_GLUE_C})
target_include_directories(minecraft_es PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${NATIVE_APP_GLUE_H})
find_library(log-lib log)
find_library(android-lib android)
find_library(EGL-lib EGL)
find_library(GLESv3-lib GLESv3)
target_link_libraries(minecraft_es glm::glm ${log-lib} ${android-lib} ${EGL-lib} ${GLESv3-lib})
